# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM sechiro/scipy-notebook

MAINTAINER Jupyter Project <jupyter@googlegroups.com>

USER root

# R and ODBC pre-requisites
RUN yum -y update && \
    yum -y install \
    fonts-dejavu \
    gcc-gfortran \
    gcc \
    glibc \
    e2fsprogs \
    krb5-libs \
    openssl

USER $NB_USER

# R packages including IRKernel which gets installed globally.
# Pin r-base to a specific build number for https://github.com/jupyter/docker-stacks/issues/210#issuecomment-246081809
RUN conda config --add channels r && \
    conda install --quiet --yes \
    'rpy2=2.8*' \
    'r-base=3.3.1 1' \
    'r-irkernel=0.6*' \
    'r-plyr=1.8*' \
    'r-devtools=1.11*' \
    'r-dplyr=0.4*' \
    'r-ggplot2=2.1*' \
    'r-tidyr=0.5*' \
    'r-shiny=0.13*' \
    'r-rmarkdown=0.9*' \
    'r-forecast=7.1*' \
    'r-stringr=1.0*' \
    'r-rsqlite=1.0*' \
    'r-reshape2=1.4*' \
    'r-nycflights13=0.2*' \
    'r-caret=6.0*' \
    'r-rcurl=1.95*' \
    'r-randomforest=4.6*' && conda clean -tipsy

COPY msodbcsql-13.0.0.0.tar.gz /tmp
